theme: jekyll-theme-minimal
title: energyc0's homepage
description: energyc0 shares here everything he's learned in the world of programming
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
