theme: jekyll-theme-minimal
title: energyc0's homepage
description: energyc0 shares here everything he's learned in the world of programming

<ul>
  {% for post in site.posts %}
    <li>
      <a href="{{ post.url }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>
